### ISSUE TITLE
Cannot run via `cargo run`

### ISSUE THREAD

**Issue by zeankundev** [MeadowlarkDAW/Meadowlark#54]
The error is here.
```
thread 'main' panicked at 'Cannot create renderer: ShaderCompileError("Vertex stage: ERROR: 0:1: '' :  Version number not supported by OGL driver\n\n")', C:\Users\Zean\.cargo\git\checkouts\vizia-a7ac1d316660c1f9\f9f06ce\crates\vizia_winit\src\window.rs:117:65
```
Expected: run smoothly

**Comment by geom3trik** [comment]
Looks like you might be trying to run on hardware that doesn't support OpenGL 3.3. Which is unusual since it's now 12 years old. Are you trying to run on a VM?

In any case the application is currently undergoing a re-write to use GTK4 for the UI. You can find the latest progress (very early) on the `gtk4` branch if you want to try it.

**Comment by zeankundev** [comment]
No. I am trying to run it on a native machine

**Comment by geom3trik** [comment]
> No. I am trying to run it on a native machine. And this problem ran on Windows 10, so native libraries like Qt is helpful.

The current iteration is using GTK4 rather than Qt. I don't know if that's native on Windows 10 or not. You could try running it on your machine but I think it may not work on Windows yet at this stage in the development.

**Comment by BillyDM** [comment]
closing because of a rewrite
